from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    # Only import the ViewSets you intend to use
    RestaurantViewSet,
    StaffViewSet,
    TableViewSet,
    ReservationViewSet,
)

# Create a router instance
router = DefaultRouter()

# Register ONLY the desired ViewSets with the router
router.register(r'restaurants', RestaurantViewSet)
router.register(r'staff', StaffViewSet)
router.register(r'tables', TableViewSet)
router.register(r'reservations', ReservationViewSet)

app_name = 'restaurantservice'

urlpatterns = [
    # Include the URLs generated by the router
    path('api/', include(router.urls)),
]